### ISSUE TITLE
Extract Error: 'MetricsName'

### ISSUE THREAD

**Issue by webaker** [singer-io/tap-doubleclick-campaign-manager#14]
Hello,

I noticed that my Stitch Integration is kicking out an error called 'MetricsName'. This is the error when I tried to re-authenticate:

2019-11-18 15:37:13,800Z   main - INFO Running tap-doubleclick-campaign-manager version 1.2.0 and target-stitch version 2.0.5
2019-11-18 15:37:13,875Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-doubleclick-campaign-manager --config /tmp/tap_discover_config.json --discover
2019-11-18 15:37:14,300Z    tap - INFO URL being requested: GET https://www.googleapis.com/discovery/v1/apis/dfareporting/v3.3/rest
2019-11-18 15:37:14,300Z    tap - INFO Attempting refresh to obtain initial access_token
2019-11-18 15:37:14,300Z    tap - INFO Refreshing access_token
2019-11-18 15:37:14,392Z    tap - INFO Starting discover
2019-11-18 15:37:14,396Z    tap - INFO URL being requested: GET https://www.googleapis.com/dfareporting/v3.3/userprofiles/4882862/reports?alt=json
2019-11-18 15:37:15,119Z    tap - CRITICAL 'metricNames'
2019-11-18 15:37:15,122Z    tap - Traceback (most recent call last):
2019-11-18 15:37:15,122Z    tap -   File "tap-env/bin/tap-doubleclick-campaign-manager", line 10, in <module>
2019-11-18 15:37:15,122Z    tap -     sys.exit(main())
2019-11-18 15:37:15,122Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/singer/utils.py", line 229, in wrapped
2019-11-18 15:37:15,122Z    tap -     return fnc(*args, **kwargs)
2019-11-18 15:37:15,122Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_doubleclick_campaign_manager/__init__.py", line 64, in main
2019-11-18 15:37:15,122Z    tap -     do_discover(service, config)
2019-11-18 15:37:15,122Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_doubleclick_campaign_manager/__init__.py", line 43, in do_discover
2019-11-18 15:37:15,122Z    tap -     catalog = discover_streams(service, config)
2019-11-18 15:37:15,122Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_doubleclick_campaign_manager/discover.py", line 38, in discover_streams
2019-11-18 15:37:15,122Z    tap -     fieldmap = get_fields(field_type_lookup, report)
2019-11-18 15:37:15,123Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_doubleclick_campaign_manager/schema.py", line 25, in get_fields
2019-11-18 15:37:15,123Z    tap -     metric_names = criteria_obj['metricNames']
2019-11-18 15:37:15,123Z    tap - KeyError: 'metricNames'
2019-11-18 15:37:15,164Z   main - INFO Tap exited abnormally with status 1
2019-11-18 15:37:15,165Z   main - INFO No tunnel subprocess to tear down
2019-11-18 15:37:15,165Z   main - INFO Exit status is: Discovery failed with code 1 and error message: "'metricNames'".

**Comment by webaker** [comment]
Still getting this error. When using different DCM accounts, the tap works fine, but this one specific account keeps throwing up this error. Have checked all DCM API and Access settings and they are setup correctly and had not changed with this error started happening.

**Comment by milesey80** [comment]
I have a similar issue, although my error appears to be specifically around reachbyfrequencymetric names:
2020-11-30 20:12:24,437Z   main - INFO Running tap-doubleclick-campaign-manager version 1.2.0 and target-stitch version 3.2.0
2020-11-30 20:12:24,614Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.extractionJobStarted ), use_ssl( true )
2020-11-30 20:12:24,616Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.extractionJobFinished ), use_ssl( true )
2020-11-30 20:12:24,617Z   main - INFO [smart-services] building smart service producer: topic( com.stitchdata.streamRecordCount ), use_ssl( true )
2020-11-30 20:12:25,631Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobStarted [47] at offset None
2020-11-30 20:12:25,631Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-doubleclick-campaign-manager --config /tmp/tap_discover_config.json --discover
2020-11-30 20:12:26,087Z    tap - INFO Attempting refresh to obtain initial access_token
2020-11-30 20:12:26,088Z    tap - INFO Refreshing access_token
2020-11-30 20:12:26,249Z    tap - INFO Starting discover
2020-11-30 20:12:26,898Z    tap - CRITICAL 'reachByFrequencyMetricNames'
2020-11-30 20:12:26,898Z    tap - Traceback (most recent call last):
2020-11-30 20:12:26,898Z    tap -   File "tap-env/bin/tap-doubleclick-campaign-manager", line 33, in <module>
2020-11-30 20:12:26,898Z    tap -     sys.exit(load_entry_point('tap-doubleclick-campaign-manager==1.2.0', 'console_scripts', 'tap-doubleclick-campaign-manager')())
2020-11-30 20:12:26,898Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/singer/utils.py", line 229, in wrapped
2020-11-30 20:12:26,899Z    tap -     return fnc(*args, **kwargs)
2020-11-30 20:12:26,899Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_doubleclick_campaign_manager/__init__.py", line 64, in main
2020-11-30 20:12:26,899Z    tap -     do_discover(service, config)
2020-11-30 20:12:26,899Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_doubleclick_campaign_manager/__init__.py", line 43, in do_discover
2020-11-30 20:12:26,899Z    tap -     catalog = discover_streams(service, config)
2020-11-30 20:12:26,899Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_doubleclick_campaign_manager/discover.py", line 38, in discover_streams
2020-11-30 20:12:26,899Z    tap -     fieldmap = get_fields(field_type_lookup, report)
2020-11-30 20:12:26,899Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_doubleclick_campaign_manager/schema.py", line 45, in get_fields
2020-11-30 20:12:26,899Z    tap -     metric_names = criteria_obj['metricNames'] + criteria_obj['reachByFrequencyMetricNames']
2020-11-30 20:12:26,899Z    tap - KeyError: 'reachByFrequencyMetricNames'
2020-11-30 20:12:26,947Z   main - INFO Tap exited abnormally with status 1
2020-11-30 20:12:27,630Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobFinished [30] at offset None
2020-11-30 20:12:27,630Z   main - INFO No tunnel subprocess to tear down
2020-11-30 20:12:27,630Z   main - INFO Exit status is: Discovery failed with code 1 and error message: "'reachByFrequencyMetricNames'".


It actually worked for one run of data last week but then has failed on all subsequent loads, even though it's now pointed at a report that doesnt contain any reach metrics. Any ideas?
thanks

**Comment by webaker** [comment]
I never figured out exactly why it didn't work, but I found that when I used floodlight dimensions in my custom DCM report, it was causing my issue. Did you add any specific dimensions or metrics to the report that didn't exist before?

**Comment by cenxiao** [comment]
> I have a similar issue, although my error appears to be specifically around reachbyfrequencymetric names:
> 2020-11-30 20:12:24,437Z main - INFO Running tap-doubleclick-campaign-manager version 1.2.0 and target-stitch version 3.2.0
> 2020-11-30 20:12:24,614Z main - INFO [smart-services] building smart service producer: topic( com.stitchdata.extractionJobStarted ), use_ssl( true )
> 2020-11-30 20:12:24,616Z main - INFO [smart-services] building smart service producer: topic( com.stitchdata.extractionJobFinished ), use_ssl( true )
> 2020-11-30 20:12:24,617Z main - INFO [smart-services] building smart service producer: topic( com.stitchdata.streamRecordCount ), use_ssl( true )
> 2020-11-30 20:12:25,631Z main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobStarted [47] at offset None
> 2020-11-30 20:12:25,631Z main - INFO Starting tap to discover schemas: tap-env/bin/tap-doubleclick-campaign-manager --config /tmp/tap_discover_config.json --discover
> 2020-11-30 20:12:26,087Z tap - INFO Attempting refresh to obtain initial access_token
> 2020-11-30 20:12:26,088Z tap - INFO Refreshing access_token
> 2020-11-30 20:12:26,249Z tap - INFO Starting discover
> 2020-11-30 20:12:26,898Z tap - CRITICAL 'reachByFrequencyMetricNames'
> 2020-11-30 20:12:26,898Z tap - Traceback (most recent call last):
> 2020-11-30 20:12:26,898Z tap - File "tap-env/bin/tap-doubleclick-campaign-manager", line 33, in
> 2020-11-30 20:12:26,898Z tap - sys.exit(load_entry_point('tap-doubleclick-campaign-manager==1.2.0', 'console_scripts', 'tap-doubleclick-campaign-manager')())
> 2020-11-30 20:12:26,898Z tap - File "/code/orchestrator/tap-env/lib/python3.5/site-packages/singer/utils.py", line 229, in wrapped
> 2020-11-30 20:12:26,899Z tap - return fnc(*args, **kwargs)
> 2020-11-30 20:12:26,899Z tap - File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_doubleclick_campaign_manager/**init**.py", line 64, in main
> 2020-11-30 20:12:26,899Z tap - do_discover(service, config)
> 2020-11-30 20:12:26,899Z tap - File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_doubleclick_campaign_manager/**init**.py", line 43, in do_discover
> 2020-11-30 20:12:26,899Z tap - catalog = discover_streams(service, config)
> 2020-11-30 20:12:26,899Z tap - File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_doubleclick_campaign_manager/discover.py", line 38, in discover_streams
> 2020-11-30 20:12:26,899Z tap - fieldmap = get_fields(field_type_lookup, report)
> 2020-11-30 20:12:26,899Z tap - File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_doubleclick_campaign_manager/schema.py", line 45, in get_fields
> 2020-11-30 20:12:26,899Z tap - metric_names = criteria_obj['metricNames'] + criteria_obj['reachByFrequencyMetricNames']
> 2020-11-30 20:12:26,899Z tap - KeyError: 'reachByFrequencyMetricNames'
> 2020-11-30 20:12:26,947Z main - INFO Tap exited abnormally with status 1
> 2020-11-30 20:12:27,630Z main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobFinished [30] at offset None
> 2020-11-30 20:12:27,630Z main - INFO No tunnel subprocess to tear down
> 2020-11-30 20:12:27,630Z main - INFO Exit status is: Discovery failed with code 1 and error message: "'reachByFrequencyMetricNames'".
> 
> It actually worked for one run of data last week but then has failed on all subsequent loads, even though it's now pointed at a report that doesnt contain any reach metrics. Any ideas?
> thanks

Hi I am getting the exact same error, did you figure it out?

**Comment by cenxiao** [comment]
I think I figured it out, this is because you have a report in Campaign Manager that is missing Metrics, and in my case, I have a REACH report that doesn't have 'Reach by Frequency' metrics. I have made a PR: https://github.com/singer-io/tap-doubleclick-campaign-manager/pull/18
