### ISSUE TITLE
Issue with new tap version (1.4)

### ISSUE THREAD

**Issue by joaopmoniz** [singer-io/tap-doubleclick-campaign-manager#24]
Hi there,

We have been using Stitch to ingest our CM data for some time, but it seems after the new version update (1.4) implemented yesterday our ingestion has been failing. I've tried to recreate the ingestion and reauthorize it, but it didn't work. Also I ran the reports manually, and also using the google cloud python library, and both are working, so I assume it might be something related the new tap version, although I wasn't able to find the issue.

This is the error message we are receiving:
```
2023-02-23 09:34:07,253Z   main - INFO State update: adding current_report = "8"
2023-02-23 09:34:07,253Z   main - INFO State update: adding reports.0.report_id = "8"
2023-02-23 09:34:07,253Z   main - INFO State update: adding reports.0.stream_alias = "campaignmanager_ca"
2023-02-23 09:34:07,253Z   main - INFO State update: adding reports.0.stream_name = "campaignmanager_ca_8"
2023-02-23 09:34:07,816Z    tap - ERROR campaignmanager_ca_8: report_id 8 / file_id 4031410504 - File status is QUEUED, processing failed
2023-02-23 09:34:07,819Z    tap - INFO "run_report" job took 0.6s, ended with status "failed"
2023-02-23 09:34:07,819Z    tap - CRITICAL campaignmanager_ca_8: report_id 8 / file_id 4031410504 - File status is QUEUED, processing failed
2023-02-23 09:34:07,819Z    tap - Traceback (most recent call last):
2023-02-23 09:34:07,820Z    tap -   File "/code/orchestrator/tap-env/bin/tap-doubleclick-campaign-manager", line 33, in <module>
2023-02-23 09:34:07,820Z    tap -     sys.exit(load_entry_point('tap-doubleclick-campaign-manager==1.4.0', 'console_scripts', 'tap-doubleclick-campaign-manager')())
2023-02-23 09:34:07,820Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/singer/utils.py", line 235, in wrapped
2023-02-23 09:34:07,820Z    tap -     return fnc(*args, **kwargs)
2023-02-23 09:34:07,820Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/tap_doubleclick_campaign_manager/__init__.py", line 67, in main
2023-02-23 09:34:07,820Z    tap -     do_sync(service, config, parsed_args.catalog, state)
2023-02-23 09:34:07,820Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/tap_doubleclick_campaign_manager/__init__.py", line 51, in do_sync
2023-02-23 09:34:07,820Z    tap -     sync_reports(service, config, catalog, state)
2023-02-23 09:34:07,820Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/tap_doubleclick_campaign_manager/sync_reports.py", line 250, in sync_reports
2023-02-23 09:34:07,820Z    tap -     sync_report(service,
2023-02-23 09:34:07,820Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/tap_doubleclick_campaign_manager/sync_reports.py", line 194, in sync_report
2023-02-23 09:34:07,820Z    tap -     raise Exception(message)
2023-02-23 09:34:07,820Z    tap - Exception: campaignmanager_ca_8: report_id 8 / file_id 4031410504 - File status is QUEUED, processing failed
2023-02-23 09:34:07,861Z target - INFO Requests complete, stopping loop
2023-02-23 09:34:07,907Z   main - INFO Target exited normally with status 0
2023-02-23 09:34:07,911Z   main - INFO No tunnel subprocess to tear down
2023-02-23 09:34:07,911Z   main - INFO Exit status is: Discovery succeeded. Tap failed with code 1 and error message: "campaignmanager_ca_8: report_id 8 / file_id 4031410504 - File status is QUEUED, processing failed". Target succeeded.
```

**Comment by dsprayberry** [comment]
Addressed via [PR 27](https://github.com/singer-io/tap-doubleclick-campaign-manager/pull/27)
